# Generated by Django 5.2.2 on 2026-01-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=20)),
                ('Marca', models.CharField(max_length=50)),
                ('Modelo', models.CharField(max_length=100)),
                ('Colores', models.CharField(max_length=150)),
                ('Precio', models.IntegerField()),
                ('Ano', models.PositiveBigIntegerField()),
            ],
        ),
    ]
