# Generated by Django 5.2.2 on 2026-02-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=50)),
                ('Mail', models.EmailField(max_length=254, null=True)),
                ('Telefono', models.CharField(max_length=12, null=True)),
                ('Rut', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='Colores',
            new_name='Color',
        ),
        migrations.AddField(
            model_name='auto',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
    ]
