# Generated by Django 5.2.2 on 2026-02-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent_App', '0002_cliente_rename_colores_auto_color_auto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Metodo_Pago',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='Color',
            field=models.CharField(max_length=30),
        ),
    ]
