# Generated by Django 5.2.2 on 2026-02-02 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent_App', '0003_cliente_metodo_pago_alter_auto_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('fase', models.CharField(default='recepcion', max_length=50)),
                ('presupuesto', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('auto_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agent_App.auto')),
            ],
        ),
    ]
