# Generated by Django 5.2.2 on 2026-02-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent_App', '0004_estadoconversacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoconversacion',
            name='mensajes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
