# Generated by Django 5.2.2 on 2026-02-10 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent_App', '0005_estadoconversacion_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos_comprados', to='Agent_App.cliente'),
        ),
    ]
