# Generated by Django 5.2.2 on 2026-02-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent_App', '0006_auto_comprador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoconversacion',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='estadoconversacion',
            name='auto_interes',
        ),
        migrations.RemoveField(
            model_name='estadoconversacion',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='estadoconversacion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estadoconversacion',
            name='presupuesto',
        ),
        migrations.AlterField(
            model_name='estadoconversacion',
            name='fase',
            field=models.CharField(default='inicio', max_length=50),
        ),
    ]
